PAP-0 PROJECT INITIALIZATION
PAPBoutique/pap-boutique-v1 pull request #1
Opened 2023-03-10 17:04 UTC by ILYASS-DEV

2023-03-13 10:52 UTC, SherlyH221 commented
Je pense que c'est bon

2023-03-16 10:30 UTC, moolsbytheway requested changes

2023-03-16 10:30 UTC, moolsbytheway commented on pap-backend/build.gradle
> +group = 'com.example'
com.pap

2023-03-20 10:04 UTC, moolsbytheway approved these changes

2023-03-20 10:04 UTC, merged