PB-5 Product creation
PAPBoutique/pap-boutique-v1 pull request #3
Opened 2023-04-26 10:41 UTC by ILYASS-DEV

2023-04-27 09:17 UTC, moolsbytheway requested changes

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/adapter/src/main/java/com/pap/adapter/ProductJpaAdapter.java
> +    public List<ProductDomainObject> getProducts() {
Remove this one

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/adapter/src/main/java/com/pap/adapter/jpa/entity/ProductEntity.java
> +    private Date CreatedDate;
utilise LocalDateTime

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/adapter/src/main/java/com/pap/adapter/jpa/entity/ProductEntity.java
> +    private Date CreatedDate;
CreatedDate doit être en camelCase

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/adapter/src/main/java/com/pap/adapter/rest/controller/ProductController.java
> +    // todo List<ProductDTO>
remove comment

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/adapter/src/main/resources/application.properties
> +version=3.0.0
version ?

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/adapter/src/main/resources/application.properties
> +spring.thymeleaf.cache=false
enlève thymleaf

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/adapter/src/main/resources/application.properties
> +#spring.datasource.initialization-mode=never
remove comment

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/adapter/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/hex
donne un nom significaf à la base de données

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/adapter/src/main/resources/application.properties
> +spring.datasource.password=password321
pas de mots de passes dans les fichiers versionnés

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/application/src/main/java/com/pap/ProductServiceImpl.java
> +public class ProductServiceImpl implements ProductServicePort {
ProductService tout simplement

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/application/src/main/java/com/pap/ProductServiceImpl.java
> +    public List<ProductDomainObject> getProducts() {
remove

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/domain/src/main/java/com/pap/model/product/ProductDomainObject.java
> +    private Integer quantity;
add createdDate

2023-04-27 09:17 UTC, moolsbytheway commented on pap-backend/domain/src/main/java/com/pap/ports/api/ProductServicePort.java
> +    List<ProductDomainObject> getProducts();
remove

2023-04-27 09:17 UTC, moolsbytheway commented on pap-frontend/package.json
> +    "start": "ng serve --proxy-config proxy.conf.json",
je pense pas que tu as besoin de celle là, il suffit de le rajouter sur angular.json

2023-04-27 15:38 UTC, ILYASS-DEV commented on pap-frontend/package.json
> +    "start": "ng serve --proxy-config proxy.conf.json",
Oui tu as raison

2023-06-05 13:31 UTC, closed without merging

2023-06-05 13:31 UTC, moolsbytheway commented
duplicate